// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetNodeInput struct {
	ID       *string `json:"id"`
	FullPath *string `json:"full_path"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MutationResult struct {
	Success bool `json:"success"`
}

type UserInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
