// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/freecloudio/server/domain/models"
)

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MutationResult struct {
	Success bool `json:"success"`
}

type NodeCreationResult struct {
	Created bool         `json:"created"`
	Node    *models.Node `json:"node"`
}

type NodeIdentifierInput struct {
	ID       *string `json:"id"`
	FullPath *string `json:"full_path"`
}

type NodeInput struct {
	ParentNodeIdentifier *NodeIdentifierInput `json:"parent_node_identifier"`
	Name                 string               `json:"name"`
	Type                 models.NodeType      `json:"type"`
}

type NodeShareResult struct {
	Created bool          `json:"created"`
	Share   *models.Share `json:"share"`
}

type ShareInput struct {
	NodeID       string           `json:"node_id"`
	SharedWithID string           `json:"shared_with_id"`
	Mode         models.ShareMode `json:"mode"`
}

type UserInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
